refactor: 2space, lint error fix

diff --git a/bin/gen_commit_files b/bin/gen_commit_files
--- a/bin/gen_commit_files
+++ b/bin/gen_commit_files
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 
-current_dir=$(pwd)
-script_dir=$(cd $(dirname $0); pwd)
+# current_dir=$(pwd)
+# script_dir=$(cd "$(dirname $0)"; pwd)
 command_name=$(basename $0)
 out_root_name=GeneratedSources
 
 commit_id=
 out_dir=
 usage() {
-    cat <<EOF
+  cat <<EOF
 Generate modified files in specify git commit id.
   Usage:
       $command_name [option] [commit_id]
@@ -22,140 +22,137 @@ Generate modified files in specify git commit id.
 EOF
 }
 
-has() {
-    which ${1} >/dev/null 2>&1
-    return $?
-}
+has() { command -v ${1} >& /dev/null; }
 
 is_win() {
-    local ostype="$OSTYPE"
-    if [[ "$ostype" == "cygwin" ]] || [[ "$ostype" == "msys" ]]; then
-        return 0
-    fi
-    return 1
+  local ostype="$OSTYPE"
+  if [[ "$ostype" == "cygwin" ]] || [[ "$ostype" == "msys" ]]; then
+    return 0
+  fi
+  return 1
 }
 
 get_git_root() {
-    git rev-parse --show-toplevel
+  git rev-parse --show-toplevel
 }
 
 get_git_head_commit_id() {
-    git rev-parse HEAD
+  git rev-parse HEAD
 }
 
 is_git_directory_for_win() {
-    local ret=0
-    if git status 2>&1 |grep "Not a git repository" >/dev/null 2>&1; then
-        ret=1
-    fi
-    return $ret
+  local ret=0
+  if git status 2>&1 |grep "Not a git repository" >/dev/null 2>&1; then
+    ret=1
+  fi
+  return $ret
 }
 
 is_git_directory() {
-    is_win && return $(is_git_directory_for_win)
-    local result=$(git rev-parse --is-inside-work-tree 2>/dev/null)
-    if [[ "$result" == "true" ]]; then
-        return 0
-    fi
-    return 1
+  is_win && return "$(is_git_directory_for_win)"
+  local result=$(git rev-parse --is-inside-work-tree 2>/dev/null)
+  if [[ "$result" == "true" ]]; then
+    return 0
+  fi
+  return 1
 }
 
 set_args() {
-    for arg in "$@"; do
-        case "$arg" in
-            -h|--help)
-                usage
-                exit 0
-                ;;
-            -o*|--out*)
-                out_dir=${arg#*=}
-                ;;
-            *)
-                commit_id="$arg"
-                ;;
-        esac
-    done
+  for arg in "$@"; do
+    case "$arg" in
+      -h|--help)
+        usage
+        exit 0
+        ;;
+      -o*|--out*)
+        out_dir=${arg#*=}
+        ;;
+      *)
+        commit_id="$arg"
+        ;;
+    esac
+  done
 }
 
 check() {
-    if ! is_git_directory; then
-        echo "Not in git directory." 1>&2
-        exit 1
-    fi
-    if [[ -z $commit_id ]]; then
-        # echo "Specify commit id." 1>&2
-        # usage
-        # git log --oneline -5
-        echo "===> Using HEAD commit .."
-        commit_id=$(get_git_head_commit_id)
-    fi
+  if ! is_git_directory; then
+    echo "Not in git directory." 1>&2
+    exit 1
+  fi
+  if [[ -z $commit_id ]]; then
+    # echo "Specify commit id." 1>&2
+    # usage
+    # git log --oneline -5
+    echo "===> Using HEAD commit .."
+    commit_id=$(get_git_head_commit_id)
+  fi
 }
 
 get_realpath() {
-    local target="$1"
-    local backup=
-    while true; do
-        local cmd='cd '$target
-        if $(eval $cmd >/dev/null 2>&1); then
-            target=$(eval $cmd && pwd)
-            break
-        fi
-        if [[ -z $target ]]; then
-            echo "error"
-            exit 1
-        fi
-        local b=$(basename $target)
-        [[ ! -z $backup ]] && backup="/$backup"
-        backup="$b$backup"
-        target=$(dirname $target)
-    done
-    local res=$target/$backup
-    if [[ "$target" == "/" ]]; then
-        res=/$backup
+  local target="$1"
+  local backup=
+  while true; do
+    local cmd='cd '$target
+    if eval $cmd >/dev/null 2>&1; then
+      target=$(eval $cmd && pwd)
+      break
     fi
-    echo $res
+    if [[ -z $target ]]; then
+      echo "error"
+      exit 1
+    fi
+    local b=$(basename $target)
+    [[ ! -z $backup ]] && backup="/$backup"
+    backup="$b$backup"
+    target=$(dirname $target)
+  done
+  local res=$target/$backup
+  if [[ "$target" == "/" ]]; then
+    res=/$backup
+  fi
+  echo $res
 }
 
 make_remove_output_dir() {
-    if [[ -z $out_dir ]]; then
-        out_dir=.
-    fi
-    out_dir="$(get_realpath $out_dir)"
-    out_dir=$out_dir/$out_root_name
-    if [[ -e $out_dir ]]; then
-        echo "===> Deleting $out_dir"
-        rm -rf $out_dir
-    fi
+  if [[ -z $out_dir ]]; then
+    out_dir=.
+  fi
+  out_dir="$(get_realpath $out_dir)"
+  out_dir=$out_dir/$out_root_name
+  if [[ -e $out_dir ]]; then
+    echo "===> Deleting $out_dir"
+    rm -rf $out_dir
+  fi
 }
 
 initialize() {
-    set_args "$@"
-    check
-    make_remove_output_dir
-    git_root=$(get_git_root)
+  set_args "$@"
+  check
+  make_remove_output_dir
+  git_root=$(get_git_root)
 }
 
 cp_file() {
-    if [[ ! -e $out_dir ]]; then
-        mkdir -p $out_dir
-    fi
-    if [[ ! -e $1 ]]; then
-        echo "==> [ NG ] $1"
-        return
-    fi
-    echo "==> [ OK ] $1"
-    cp --parent "$1" $out_dir
+  if [[ ! -e $out_dir ]]; then
+    mkdir -p $out_dir
+  fi
+  if [[ ! -e $1 ]]; then
+    echo "==> [ NG ] $1"
+    return
+  fi
+  echo "==> [ OK ] $1"
+  cp --parent "$1" $out_dir
 }
 
 main() {
-    initialize "$@"
-    cd $git_root
-    # modified_files=$(git diff-tree --no-commit-id --name-only -r $commit_id)
-    modified_files=$(git show --pretty="" --name-only $commit_id)
-    for f in $modified_files; do
-        cp_file "$f"
-    done
-    echo "===> Modified files committed in $commit_id generated in $out_dir. done."
+  initialize "$@"
+  cd $git_root
+  # modified_files=$(git diff-tree --no-commit-id --name-only -r $commit_id)
+  modified_files=$(git show --pretty="" --name-only $commit_id)
+  for f in $modified_files; do
+    cp_file "$f"
+  done
+  echo "===> Modified files committed in $commit_id generated in $out_dir. done."
 }
 main "$@"
 
diff --git a/bin/gpr b/bin/gpr
--- a/bin/gpr
+++ b/bin/gpr
@@ -2,60 +2,61 @@
 
 target=$1
 _exe() {
-    cmd=$*
-    # rc=1
-    # result=
-    echo "==> $cmd"
-    # result=$($cmd 2>&1) && rc=0
-    # if [[ $rc -ne 0 ]]; then
-    if ! $cmd; then
-        echo "!!Abort!! while updating $target cmd: $cmd"
-        # echo "      ==> $result"
-        exit 1
-    fi
+  cmd=$*
+  # rc=1
+  # result=
+  echo "==> $cmd"
+  # result=$($cmd 2>&1) && rc=0
+  # if [[ $rc -ne 0 ]]; then
+  if ! $cmd; then
+    echo "!!Abort!! while updating $target cmd: $cmd"
+    # echo "      ==> $result"
+    exit 1
+  fi
 }
 is_git_svned_repo() {
-    [ -e $(git rev-parse --show-toplevel)/.git/svn ]
+  [ -e "$(git rev-parse --show-toplevel)/.git/svn" ]
 }
 is_inside_repo() {
-    git rev-parse --is-inside-work-tree >/dev/null 2>&1
+  git rev-parse --is-inside-work-tree >/dev/null 2>&1
 }
 main() {
-    ! is_inside_repo && echo "Not in repository." 1>&2 && exit 1
-    if [[ ! -z $target ]]; then
-        cd $target
+  ! is_inside_repo && echo "Not in repository." 1>&2 && exit 1
+  if [[ ! -z $target ]]; then
+    cd $target
+  fi
+  local modified=$(git status -s)
+  local stash=0
+  # local stash_msg=""
+  if [[ "$modified" != "" ]]; then
+    # local shuld_stash=$(echo "$modified" | grep -v '??' | wc -l)
+    local shuld_stash=$(echo "$modified" | grep -c -v '??')
+    if [[ $shuld_stash -gt 0 ]]; then
+      stash=1
+      # stash_msg="(with_stash)"
+      _exe git stash -q
     fi
-    local modified=$(git status -s)
-    local stash=0
-    # local stash_msg=""
-    if [[ "$modified" != "" ]]; then
-        local shuld_stash=$(echo "$modified" | grep -v '??' | wc -l)
-        if [[ $shuld_stash -gt 0 ]]; then
-            stash=1
-            # stash_msg="(with_stash)"
-            _exe git stash -q
-        fi
-    fi
-    if is_git_svned_repo; then
-        _exe git svn rebase
-    else
-        _exe git pull --rebase
-    fi
-    # local nochanged=$(echo "$result" | grep "up to date" | wc -l)
-    # local update_msg="up-to-date"
-    # if [[ $nochanged -eq 0 ]]; then
-    #     update_msg="pulled"
-    # fi
-    if [[ $stash -eq 1 ]]; then
-        _exe git stash pop -q
-    fi
-    # echo "==> Success to update ($update_msg) $stash_msg $target"
-    if [[ "$modified" != "" ]]; then
-        echo "$modified"
-    fi
-    if [[ ! -z $target ]]; then
-        cd - >/dev/null 2>&1
-    fi
+  fi
+  if is_git_svned_repo; then
+    _exe git svn rebase
+  else
+    _exe git pull --rebase
+  fi
+  # local nochanged=$(echo "$result" | grep "up to date" | wc -l)
+  # local update_msg="up-to-date"
+  # if [[ $nochanged -eq 0 ]]; then
+  #     update_msg="pulled"
+  # fi
+  if [[ $stash -eq 1 ]]; then
+    _exe git stash pop -q
+  fi
+  # echo "==> Success to update ($update_msg) $stash_msg $target"
+  if [[ "$modified" != "" ]]; then
+    echo "$modified"
+  fi
+  if [[ ! -z $target ]]; then
+    cd - >/dev/null 2>&1
+  fi
 }
-main $*
+main "$@"
 
diff --git a/bin/pullall b/bin/pullall
--- a/bin/pullall
+++ b/bin/pullall
@@ -2,51 +2,52 @@
 
 root_dir=${1:-~/works/50_src}
 _exe() {
-    cmd=$*
-    rc=1
-    result=
-    result=$($cmd 2>&1) && rc=0
-    if [[ $rc -ne 0 ]]; then
-        echo "!!Abort!! while updating $target cmd: $cmd"
-        echo "      ==> $result"
-        exit 1
-    fi
+  cmd=$*
+  rc=1
+  result=
+  result=$($cmd 2>&1) && rc=0
+  if [[ $rc -ne 0 ]]; then
+    echo "!!Abort!! while updating $target cmd: $cmd"
+    echo "      ==> $result"
+    exit 1
+  fi
 }
 _pull() {
-    target=$1
-    cd $target
-    local modified=$(git status -s)
-    local stash=0
-    local stash_msg=""
-    if [[ "$modified" != "" ]]; then
-        local shuld_stash=$(echo "$modified" | grep -v '??' | wc -l)
-        if [[ $shuld_stash -gt 0 ]]; then
-            stash=1
-            stash_msg="(with_stash)"
-            _exe git stash -q
-        fi
+  target=$1
+  cd $target
+  local modified=$(git status -s)
+  local stash=0
+  local stash_msg=""
+  if [[ "$modified" != "" ]]; then
+    local shuld_stash=$(echo "$modified" | grep -c -v '??')
+    if [[ $shuld_stash -gt 0 ]]; then
+      stash=1
+      stash_msg="(with_stash)"
+      _exe git stash -q
     fi
-    _exe git pull --rebase
-    local nochanged=$(echo "$result" | grep "up to date" | wc -l)
-    local update_msg="up-to-date"
-    if [[ $nochanged -eq 0 ]]; then
-        update_msg="pulled"
-    fi
-    if [[ $stash -eq 1 ]]; then
-        _exe git stash pop -q
-    fi
-    echo "==> Success to update ($update_msg) $stash_msg $target"
-    if [[ "$modified" != "" ]]; then
-        echo "$modified"
-    fi
-    cd - >/dev/null 2>&1
+  fi
+  _exe git pull --rebase
+  local nochanged=$(echo "$result" | grep -c "up to date")
+  local update_msg="up-to-date"
+  if [[ $nochanged -eq 0 ]]; then
+    update_msg="pulled"
+  fi
+  if [[ $stash -eq 1 ]]; then
+    _exe git stash pop -q
+  fi
+  echo "==> Success to update ($update_msg) $stash_msg $target"
+  if [[ "$modified" != "" ]]; then
+    echo "$modified"
+  fi
+  cd - >/dev/null 2>&1
 }
 main() {
-    for f in `find $root_dir -maxdepth 3 -name ".git" -type d`; do
-        dir=$(basename $(dirname $f))
-        dir=$(cd $root_dir/$dir && pwd)
-        _pull $dir
+  find $root_dir -maxdepth 3 -name ".git" -type d |
+    while read -r f; do
+      dir=$(basename "$(dirname $f)")
+      dir=$(cd $root_dir/$dir && pwd)
+      _pull $dir
     done
-    echo "Done."
+  echo "Done."
 }
-main $*
+main "$@"
