feat(bin): mine: Change to No exit if not exists file/directory specified

diff --git a/bin/mine b/bin/mine
--- a/bin/mine
+++ b/bin/mine
@@ -40,8 +40,8 @@ initialize() {
 }
 sub() {
   if [[ ! -e $f || $f == / ]]; then
-    echo "=> Invalid target. $f" 1>&2
-    exit 1
+    echo "=> Invalid target. $f skip" 1>&2
+    return
   fi
   if [[ $force -ne 1 ]]; then
     echo "=> Changing Owner $u.$g $f with R option...(Enter to continue)" 1>&2
