bin tool add, vim tmux zsh.... add bin...

diff --git a/bin/ssh-key-gen b/bin/ssh-key-gen
--- a/bin/ssh-key-gen
+++ b/bin/ssh-key-gen
@@ -5,6 +5,7 @@ read email
 if [ ! "$email" = "" ]; then
     ssh-keygen -t rsa -b 4096 -C "$email"
 else
-    echo "abort..."
+    echo "abort..." 1>&2
+    exit 1
 fi
 
